AWSTemplateFormatVersion: "2010-09-09"
Transform:
  - AWS::LanguageExtensions
  - AWS::Serverless-2016-10-31

Parameters:
  Project:
    Type: String
    Default: mcp
  Environment:
    Type: String
    Default: dev
  ServerName:
    Type: String
    Default: demo
  ServerVersion:
    Type: String
    Default: "1.0.0"
  Instructions:
    Type: String
    Default: "Use this MCP server to demonstrate MCP functionalities."
  DomainName:
    Type: String
    Description: "The domain name of the endpoint"
    Default: ""
  AcmCertificateArn:
    Type: String
    Description: "The certificate arn for the domain name provided"
    Default: ""
  AuthenticationType:
    Type: String
    Description: "Authentication type for the MCP server"
    Default: "DISABLED"
    AllowedValues:
      - 'DISABLED'
      - 'TOKEN_OPTIONAL'
      - 'TOKEN_REQUIRED'
      - 'OAUTH'
  OAuthIssuerUrl:
    Type: String
    Description: "The issuer URL for OAuth authentication"
    Default: ""
  OAuthAuthorizationUrl:
    Type: String
    Description: "The authorization URL for OAuth authentication"
    Default: ""
  OAuthTokenUrl:
    Type: String
    Description: "The token URL for OAuth authentication"
    Default: ""
  OAuthRevocationUrl:
    Type: String
    Description: "The revocation URL for OAuth authentication"
    Default: ""
  OAuthRedirectUris:
    Type: CommaDelimitedList
    Description: "The redirect URIs for OAuth authentication"
    Default: ""

Conditions:
  IsDomainProvided: !Not [!Equals [!Ref DomainName, ""]]

Globals:
  Api:
    TracingEnabled: true
  Function:
    Tracing: Active
    Runtime: nodejs22.x
    CodeUri: src/
    Tags:
      Project: !Ref Project
      Environment: !Ref Environment
      ServiceName: MCP

Resources:
  RestApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "${Project}-${Environment}-mcp"
      StageName: !Ref Environment
      Domain: !If
        - IsDomainProvided
        - DomainName: !Ref DomainName
          CertificateArn: !Ref AcmCertificateArn
          EndpointConfiguration: REGIONAL
        - !Ref AWS::NoValue
      DisableExecuteApiEndpoint: !If [IsDomainProvided, true, false]
      Tags:
        Project: !Ref Project
        Environment: !Ref Environment
        ServiceName: MCP

  McpFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Project}-${Environment}-mcp"
      Handler: index.handler
      MemorySize: 512
      Timeout: 900
      Environment:
        Variables:
          SSM_PREFIX: !Sub "/${Project}-${Environment}/"
          TOOLS_SSM_PREFIX: !Sub "/${Project}-${Environment}/tools/"
          RESOURCES_SSM_PREFIX: !Sub "/${Project}-${Environment}/resources/"
          PROMPTS_SSM_PREFIX: !Sub "/${Project}-${Environment}/prompts/"
          TOOL_LAMBDA_PREFIX: !Sub "${Project}-${Environment}-tools-"
          SERVER_NAME: !Ref ServerName
          SERVER_VERSION: !Ref ServerVersion
          INSTRUCTIONS: !Ref Instructions
          AUTHENTICATION_TYPE: !Ref AuthenticationType
          OAUTH_ISSUER_URL: !Ref OAuthIssuerUrl
          OAUTH_AUTHORIZATION_URL: !Ref OAuthAuthorizationUrl
          OAUTH_TOKEN_URL: !Ref OAuthTokenUrl
          OAUTH_REVOCATION_URL: !Ref OAuthRevocationUrl
          OAUTH_REDIRECT_URIS: !Join [',', !Ref OAuthRedirectUris]
      Policies:
        - Statement:
          - Effect: "Allow"
            Action: "ssm:GetParametersByPath"
            Resource: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${Project}-${Environment}/"
          - Effect: "Allow"
            Action: "lambda:InvokeFunction"
            Resource: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${Project}-${Environment}-tools-*"
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /mcp
            Method: ANY
            RestApiId: !Ref RestApi

Outputs:
  ServerEndpoint:
    Description: "MCP Server Endpoint"
    Value: !If
      - IsDomainProvided
      - !Sub "https://${DomainName}/mcp"
      - !Sub "https://${RestApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/mcp"
